server:
  port: 8080
  
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: deping-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deping_db
    username: postgres
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  security:
    access-token-key: ${ACCESS_TOKEN_KEY:8cfe790badd33fc5655c7a1f713b7fde3142fe6c204e21a19ba64defb43edf46}
    refresh-token-key: ${REFRESH_TOKEN_KEY:8cfe790badd33fc5655c7a1f713b7fde3142fe6c204e21a19ba64defb43edf46}
  hiero:
    account-id: ${HIERO_ACCOUNT_ID}
    private-key: ${HIERO_PRIVATE_KEY}
    network:
      name: ${HIERO_NETWORK}

deping:
  client-url: ${CLIENT_URL:http://localhost:4200}
